name: "Terraform CI/CD Azure"

on:
  push:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_admin_ip: "0.0.0.0/0"
  
  # ON FORCE LA TAILLE DE LA VM ICI POUR ÉVITER L'ERREUR DE STOCK (SKU)
  TF_VAR_vm_size: "Standard_DS1_v2" 
  
  # CHEMINS DES CLÉS DANS TON PROJET GITHUB
  TF_VAR_bastion_public_key_path: "./keys/bastion-vm_key.pem.pub"
  TF_VAR_web_public_key_path: "./keys/web-vm_key.pem.pub"
  TF_VAR_db_public_key_path: "./keys/db-vm_key.pem.pub" 

jobs:
  terraform:
    name: "Terraform Job"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: TFSec Check
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Plan
        run: terraform plan -lock=false -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -lock=false -input=false